drivers: iommu: eswin: eic7700-sid: Resolve compilation error
Error:
-------
./include/linux/of.h:1400: note: macro "of_property_for_each_u32" defined here
 1400 | #define of_property_for_each_u32(np, propname, u)                       \
      |
drivers/iommu/eswin/eic7700-sid.c:631:9: error: 'of_property_for_each_u32' undeclared (first use in this function); did you mean 'of_property_read_u32'?
  631 |         of_property_for_each_u32(node, "tbus", prop, cur, tbu_id) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
      |         of_property_read_u32

Resolution:
-----------
As per commit 7ae52c43f910ddc54ac6ca59743fe088751ba1ad, the number of
parameters in function "of_property_for_each_u32" is changed from 5
to 3. So updated the driver accordingly

Signed-off-by: Pritesh Patel <pritesh.patel@einfochips.com>